# permissions for end users to view useridentities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: useridentity-viewer-role
rules:
- apiGroups:
  - identity.company.org
  resources:
  - useridentities
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - identity.company.org
  resources:
  - useridentities/status
  verbs:
  - get
