# permissions for end users to edit useridentityv2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: useridentityv2-editor-role
rules:
- apiGroups:
  - identity.company.org
  resources:
  - useridentityv2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - identity.company.org
  resources:
  - useridentityv2s/status
  verbs:
  - get
