apiVersion: identity.company.org/v3
kind: UserIdentityV3
metadata:
  name: useridentityv3-sample
spec:
  template:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: user-{{ .user }}
    subjects:
    - kind: ServiceAccount
      name: sa-{{ .serviceAccountName }}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: event-view
  - apiVersion: core.cnrm.cloud.google.com/v1beta1
    kind: ServiceAccount
    metadata:
      name: sa-{{ .serviceAccountName }}
